# Generated by Django 4.0 on 2021-12-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='nombre', max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='NivelRes',
            fields=[
                ('nivel', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('last_login', models.CharField(max_length=50, null=True)),
                ('is_authenticated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supergame.nivelres')),
            ],
        ),
    ]
