# Generated by Django 4.0 on 2021-12-18 20:36

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=80, verbose_name=django.forms.widgets.Textarea)),
                ('presio', models.IntegerField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
