# Generated by Django 4.0 on 2021-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0002_juegos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegos',
            name='video',
        ),
        migrations.AlterField(
            model_name='juegos',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
    ]
