# Generated by Django 4.0 on 2021-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0003_remove_juegos_video_alter_juegos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='juegos'),
        ),
    ]
