# Generated by Django 4.0 on 2021-12-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0004_alter_juegos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='descripcion',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='titulo',
            field=models.CharField(max_length=15),
        ),
    ]
