# Generated by Django 4.0 on 2021-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0005_alter_juegos_descripcion_alter_juegos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
