# Generated by Django 4.0 on 2021-12-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0006_alter_usuarios_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
