# Generated by Django 4.0 on 2021-12-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0007_nuevos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nuevos',
        ),
    ]
