# Generated by Django 4.0 on 2021-12-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supergame', '0009_alter_juegos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='titulo',
            field=models.CharField(max_length=13),
        ),
    ]
